name: my first workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Running multiple
              run: |
               echo "My first github actions"
               ls -ltra
               cat README.md